[package]
name = "accounting-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.19", features = ["full"] }
csv = "1.1"
serde = { version = "1", features = ["derive"] }
rust_decimal = "1.25"
rust_decimal_macros = "1.25"
